# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'db_gui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1023, 963)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setStatusTip("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_sql = QtWidgets.QWidget()
        self.tab_sql.setObjectName("tab_sql")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_sql)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.textEdit = QtWidgets.QTextEdit(self.tab_sql)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.textEdit.setFont(font)
        self.textEdit.setFrameShape(QtWidgets.QFrame.Box)
        self.textEdit.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_3.addWidget(self.textEdit)
        self.tabWidget.addTab(self.tab_sql, "")
        self.tab_plot = QtWidgets.QWidget()
        self.tab_plot.setObjectName("tab_plot")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_plot)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_plothisto = QtWidgets.QPushButton(self.tab_plot)
        self.btn_plothisto.setObjectName("btn_plothisto")
        self.gridLayout_2.addWidget(self.btn_plothisto, 1, 1, 1, 1)
        self.btn_plotcurve = QtWidgets.QPushButton(self.tab_plot)
        self.btn_plotcurve.setObjectName("btn_plotcurve")
        self.gridLayout_2.addWidget(self.btn_plotcurve, 2, 1, 1, 1)
        self.tabWidget.addTab(self.tab_plot, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.formLayout = QtWidgets.QFormLayout(self.tab)
        self.formLayout.setObjectName("formLayout")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.lineEdit_url = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_url.setObjectName("lineEdit_url")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_url)
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.lineEdit_browser = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_browser.setObjectName("lineEdit_browser")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_browser)
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.pushButton)
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_salary = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_salary.setStyleSheet("font: 11pt \"Source Code Pro\";")
        self.lineEdit_salary.setText("")
        self.lineEdit_salary.setObjectName("lineEdit_salary")
        self.gridLayout.addWidget(self.lineEdit_salary, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        self.lineEdit_type = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_type.setStyleSheet("font: 11pt \"Source Code Pro\";")
        self.lineEdit_type.setText("")
        self.lineEdit_type.setObjectName("lineEdit_type")
        self.gridLayout.addWidget(self.lineEdit_type, 5, 3, 1, 1)
        self.lineEdit_degree = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_degree.setStyleSheet("font: 11pt \"Source Code Pro\";")
        self.lineEdit_degree.setText("")
        self.lineEdit_degree.setObjectName("lineEdit_degree")
        self.gridLayout.addWidget(self.lineEdit_degree, 3, 3, 1, 1)
        self.lineEdit_title = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_title.setStyleSheet("font: 11pt \"Source Code Pro\";")
        self.lineEdit_title.setText("")
        self.lineEdit_title.setObjectName("lineEdit_title")
        self.gridLayout.addWidget(self.lineEdit_title, 1, 1, 1, 1)
        self.lineEdit_workyears = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_workyears.setStyleSheet("font: 11pt \"Source Code Pro\";")
        self.lineEdit_workyears.setText("")
        self.lineEdit_workyears.setObjectName("lineEdit_workyears")
        self.gridLayout.addWidget(self.lineEdit_workyears, 1, 3, 1, 1)
        self.lineEdit_position = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_position.setStyleSheet("font: 11pt \"Source Code Pro\";")
        self.lineEdit_position.setText("")
        self.lineEdit_position.setObjectName("lineEdit_position")
        self.gridLayout.addWidget(self.lineEdit_position, 5, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 4, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.lineEdit_connect = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_connect.setFont(font)
        self.lineEdit_connect.setObjectName("lineEdit_connect")
        self.verticalLayout.addWidget(self.lineEdit_connect)
        self.horizontalLayout_btn = QtWidgets.QHBoxLayout()
        self.horizontalLayout_btn.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_btn.setSpacing(0)
        self.horizontalLayout_btn.setObjectName("horizontalLayout_btn")
        self.btn_connect = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_connect.sizePolicy().hasHeightForWidth())
        self.btn_connect.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_connect.setFont(font)
        self.btn_connect.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_connect.setCheckable(True)
        self.btn_connect.setObjectName("btn_connect")
        self.horizontalLayout_btn.addWidget(self.btn_connect)
        self.btn_search = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_search.sizePolicy().hasHeightForWidth())
        self.btn_search.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_search.setFont(font)
        self.btn_search.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_search.setObjectName("btn_search")
        self.horizontalLayout_btn.addWidget(self.btn_search)
        self.btn_clear = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_clear.sizePolicy().hasHeightForWidth())
        self.btn_clear.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_clear.setFont(font)
        self.btn_clear.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_clear.setObjectName("btn_clear")
        self.horizontalLayout_btn.addWidget(self.btn_clear)
        self.btn_exec = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(27)
        self.btn_exec.setFont(font)
        self.btn_exec.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_exec.setMouseTracking(False)
        self.btn_exec.setStatusTip("")
        self.btn_exec.setFlat(False)
        self.btn_exec.setObjectName("btn_exec")
        self.horizontalLayout_btn.addWidget(self.btn_exec)
        self.btn_load = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_load.sizePolicy().hasHeightForWidth())
        self.btn_load.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_load.setFont(font)
        self.btn_load.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_load.setObjectName("btn_load")
        self.horizontalLayout_btn.addWidget(self.btn_load)
        self.btn_next = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_next.sizePolicy().hasHeightForWidth())
        self.btn_next.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_next.setFont(font)
        self.btn_next.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_next.setToolTip("")
        self.btn_next.setObjectName("btn_next")
        self.horizontalLayout_btn.addWidget(self.btn_next)
        self.btn_up = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_up.sizePolicy().hasHeightForWidth())
        self.btn_up.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_up.setFont(font)
        self.btn_up.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_up.setObjectName("btn_up")
        self.horizontalLayout_btn.addWidget(self.btn_up)
        self.verticalLayout.addLayout(self.horizontalLayout_btn)
        self.label_res = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_res.setFont(font)
        self.label_res.setObjectName("label_res")
        self.verticalLayout.addWidget(self.label_res)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setRowCount(30)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(26, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(27, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(28, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(29, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 7, item)
        self.verticalLayout.addWidget(self.tableWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1023, 31))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.menu_File.setFont(font)
        self.menu_File.setObjectName("menu_File")
        self.menuPLOT = QtWidgets.QMenu(self.menubar)
        self.menuPLOT.setObjectName("menuPLOT")
        self.menuSalary = QtWidgets.QMenu(self.menuPLOT)
        self.menuSalary.setObjectName("menuSalary")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.statusbar.setAcceptDrops(True)
        self.statusbar.setAutoFillBackground(True)
        self.statusbar.setStyleSheet("font: 11pt \"Source Code Pro\";\n"
"")
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actioncurve = QtWidgets.QAction(MainWindow)
        self.actioncurve.setObjectName("actioncurve")
        self.actionHistogram = QtWidgets.QAction(MainWindow)
        self.actionHistogram.setObjectName("actionHistogram")
        self.actiondot = QtWidgets.QAction(MainWindow)
        self.actiondot.setCheckable(False)
        self.actiondot.setObjectName("actiondot")
        self.actioncircle = QtWidgets.QAction(MainWindow)
        self.actioncircle.setObjectName("actioncircle")
        self.menuSalary.addAction(self.actioncurve)
        self.menuSalary.addAction(self.actionHistogram)
        self.menuSalary.addAction(self.actiondot)
        self.menuSalary.addAction(self.actioncircle)
        self.menuPLOT.addAction(self.menuSalary.menuAction())
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menuPLOT.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.btn_load.released.connect(MainWindow.btn_load_released)
        self.btn_clear.released.connect(MainWindow.btn_clear_released)
        self.btn_search.released.connect(MainWindow.btn_search_released)
        self.btn_up.released.connect(MainWindow.btn_up_released)
        self.btn_next.released.connect(MainWindow.btn_next_released)
        self.btn_exec.released.connect(MainWindow.btn_execute_released)
        self.btn_connect.released.connect(MainWindow.btn_connect_released)
        self.btn_plothisto.released.connect(MainWindow.btn_plothisto_released)
        self.pushButton.released.connect(MainWindow.btn_browser_released)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SQL viewer v1.0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_sql), _translate("MainWindow", "SQL"))
        self.btn_plothisto.setText(_translate("MainWindow", "Histogram"))
        self.btn_plotcurve.setText(_translate("MainWindow", "Curve"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_plot), _translate("MainWindow", "PLOT"))
        self.label_7.setText(_translate("MainWindow", "URL"))
        self.lineEdit_url.setText(_translate("MainWindow", "http://www.baidu.com"))
        self.label_8.setText(_translate("MainWindow", "Browser"))
        self.lineEdit_browser.setText(_translate("MainWindow", "/opt/google/chrome/chrome"))
        self.pushButton.setText(_translate("MainWindow", "OpenWithBrowser"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Browser"))
        self.label_3.setText(_translate("MainWindow", "position"))
        self.label_2.setText(_translate("MainWindow", "salary"))
        self.label.setText(_translate("MainWindow", "title"))
        self.label_4.setText(_translate("MainWindow", "workyears"))
        self.label_5.setText(_translate("MainWindow", "degree"))
        self.label_6.setText(_translate("MainWindow", "type"))
        self.lineEdit_connect.setText(_translate("MainWindow", "host=192.168.228.136, user=root, passwd=root, db=article_spider, tab=lagou_job"))
        self.btn_connect.setText(_translate("MainWindow", "Connnect"))
        self.btn_search.setText(_translate("MainWindow", "&Search"))
        self.btn_clear.setText(_translate("MainWindow", "Clear"))
        self.btn_exec.setText(_translate("MainWindow", "EXECUTE"))
        self.btn_load.setText(_translate("MainWindow", "Load"))
        self.btn_next.setText(_translate("MainWindow", "Next 10"))
        self.btn_up.setText(_translate("MainWindow", "Up 10"))
        self.label_res.setText(_translate("MainWindow", "Results:"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "10"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "11"))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "12"))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "13"))
        item = self.tableWidget.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "14"))
        item = self.tableWidget.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "15"))
        item = self.tableWidget.verticalHeaderItem(15)
        item.setText(_translate("MainWindow", "16"))
        item = self.tableWidget.verticalHeaderItem(16)
        item.setText(_translate("MainWindow", "17"))
        item = self.tableWidget.verticalHeaderItem(17)
        item.setText(_translate("MainWindow", "18"))
        item = self.tableWidget.verticalHeaderItem(18)
        item.setText(_translate("MainWindow", "19"))
        item = self.tableWidget.verticalHeaderItem(19)
        item.setText(_translate("MainWindow", "20"))
        item = self.tableWidget.verticalHeaderItem(20)
        item.setText(_translate("MainWindow", "21"))
        item = self.tableWidget.verticalHeaderItem(21)
        item.setText(_translate("MainWindow", "22"))
        item = self.tableWidget.verticalHeaderItem(22)
        item.setText(_translate("MainWindow", "23"))
        item = self.tableWidget.verticalHeaderItem(23)
        item.setText(_translate("MainWindow", "24"))
        item = self.tableWidget.verticalHeaderItem(24)
        item.setText(_translate("MainWindow", "25"))
        item = self.tableWidget.verticalHeaderItem(25)
        item.setText(_translate("MainWindow", "26"))
        item = self.tableWidget.verticalHeaderItem(26)
        item.setText(_translate("MainWindow", "27"))
        item = self.tableWidget.verticalHeaderItem(27)
        item.setText(_translate("MainWindow", "28"))
        item = self.tableWidget.verticalHeaderItem(28)
        item.setText(_translate("MainWindow", "29"))
        item = self.tableWidget.verticalHeaderItem(29)
        item.setText(_translate("MainWindow", "30"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "title"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "job_salary"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "job_position"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "job_type"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "job_degree"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "job_workyears"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "job_url"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "job_desc"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(0, 4)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(0, 5)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(0, 6)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(0, 7)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(1, 3)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(1, 4)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(1, 5)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(1, 6)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(1, 7)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(2, 2)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(2, 3)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(2, 4)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(2, 5)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(2, 6)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(2, 7)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(3, 2)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(3, 3)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(3, 4)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(3, 5)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(3, 6)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(3, 7)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(4, 1)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(4, 2)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(4, 3)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(4, 4)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(4, 5)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(4, 6)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(4, 7)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(5, 1)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(5, 2)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(5, 3)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(5, 4)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(5, 5)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(5, 6)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(5, 7)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(6, 0)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(6, 1)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(6, 2)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(6, 3)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(6, 4)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(6, 5)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(6, 6)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(6, 7)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(7, 0)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(7, 1)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(7, 2)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(7, 3)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(7, 4)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(7, 5)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(7, 6)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(7, 7)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(8, 0)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(8, 1)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(8, 2)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(8, 3)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(8, 4)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(8, 5)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(8, 6)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(8, 7)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(9, 0)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(9, 1)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(9, 2)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(9, 3)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(9, 4)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(9, 5)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(9, 6)
        item.setText(_translate("MainWindow", "示例"))
        item = self.tableWidget.item(9, 7)
        item.setText(_translate("MainWindow", "示例"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.menuPLOT.setTitle(_translate("MainWindow", "PLOT"))
        self.menuSalary.setTitle(_translate("MainWindow", "Salary"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actioncurve.setText(_translate("MainWindow", "curve"))
        self.actionHistogram.setText(_translate("MainWindow", "Histogram"))
        self.actiondot.setText(_translate("MainWindow", "dot"))
        self.actioncircle.setText(_translate("MainWindow", "circle"))

